function zVisualize_ex01(prmLTE, txSig, rxSig)
% Constellation Scopes & Spectral Analyzers
persistent hScope1 hSpecAnalyzer
% Constellation Diagrams
if isempty(hScope1)
hScope1 = comm.ConstellationDiagram('ShowReferenceConstellation', false,...
    'YLimits', [-3,3], 'XLimits', [-3,3], 'Position', ...
    figposition([5 60 20 25]), 'Name', 'After Channel Model');
% Spectrum Scope
hSpecAnalyzer = dsp.SpectrumAnalyzer('SampleRate',  prmLTE.chanSRate, ...
    'SpectrumType', 'Power density', 'PowerUnits', 'dBW', ...
    'RBWSource', 'Property',   'RBW', 15000,...
    'FrequencySpan', 'Span and center frequency',...
    'Span',  0.5*prmLTE.chanSRate, 'CenterFrequency', 0,...
    'SpectralAverages', 10, ...
    'Title', 'Transmitted & Received Signal Spectrum', 'YLimits', [-80 -55],...
    'YLabel', 'PSD');
end
% Update Spectrum scope
step(hSpecAnalyzer, [txSig, rxSig]);
% Update Constellation Scope
step(hScope1, rxSig);
end